# One-to-Many and Many-to-Many Joins - Lab

## Introduction

In this lab, you'll practice your knowledge on one-to-many and many-to-many relationships!

## Objectives

You will be able to:
- Query data using one-to-many and many-to-many joins
- Predict the resulting size of one-to-many and many-to-many joins

## One-to-Many and Many-to-Many Joins
<img src='images/Database-Schema.png' width="600">

## Connect to the Database

In [2]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('data.sqlite')
c = conn.cursor()

## Employees and their Office (a One-to-One join)

Return a list of all of the employees with their first name, last name and the city and state of the office that they work out of (if they have one). Include all employees and order them by their first name, then their last name.

In [3]:
c = conn.cursor()
sql_str = """

SELECT employees.firstName, employees.lastName, offices.city, offices.state
FROM employees
JOIN offices 
ON employees.officeCode = offices.officeCode
ORDER BY employees.firstName, employees.lastName, offices.city, offices.state;

"""

c.execute(sql_str).fetchall()

[('Andy', 'Fixter', 'Sydney', ''),
 ('Anthony', 'Bow', 'San Francisco', 'CA'),
 ('Barry', 'Jones', 'London', ''),
 ('Diane', 'Murphy', 'San Francisco', 'CA'),
 ('Foon Yue', 'Tseng', 'NYC', 'NY'),
 ('George', 'Vanauf', 'NYC', 'NY'),
 ('Gerard', 'Bondur', 'Paris', ''),
 ('Gerard', 'Hernandez', 'Paris', ''),
 ('Jeff', 'Firrelli', 'San Francisco', 'CA'),
 ('Julie', 'Firrelli', 'Boston', 'MA'),
 ('Larry', 'Bott', 'London', ''),
 ('Leslie', 'Jennings', 'San Francisco', 'CA'),
 ('Leslie', 'Thompson', 'San Francisco', 'CA'),
 ('Loui', 'Bondur', 'Paris', ''),
 ('Mami', 'Nishi', 'Tokyo', 'Chiyoda-Ku'),
 ('Martin', 'Gerard', 'Paris', ''),
 ('Mary', 'Patterson', 'San Francisco', 'CA'),
 ('Pamela', 'Castillo', 'Paris', ''),
 ('Peter', 'Marsh', 'Sydney', ''),
 ('Steve', 'Patterson', 'Boston', 'MA'),
 ('Tom', 'King', 'Sydney', ''),
 ('William', 'Patterson', 'Sydney', ''),
 ('Yoshimi', 'Kato', 'Tokyo', 'Chiyoda-Ku')]

## Customers and their Orders (a One-to-Many join)

Return a list of all the customers first and last names along with a record for each of their order numbers, order dates and statuses.

In [4]:
c = conn.cursor()
sql_str = """

SELECT employees.firstName, employees.lastName, orders.orderNumber, orders.orderDate, orders.status
FROM employees
JOIN customers 
ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN orders
ON customers.customerNumber = orders.customerNumber
ORDER BY employees.firstName, employees.lastName, orders.orderNumber, orders.orderDate, orders.status;

"""

c.execute(sql_str).fetchall()

[('Andy', 'Fixter', '10120', '2003-04-29', 'Shipped'),
 ('Andy', 'Fixter', '10125', '2003-05-21', 'Shipped'),
 ('Andy', 'Fixter', '10139', '2003-07-16', 'Shipped'),
 ('Andy', 'Fixter', '10148', '2003-09-11', 'Shipped'),
 ('Andy', 'Fixter', '10152', '2003-09-25', 'Shipped'),
 ('Andy', 'Fixter', '10169', '2003-11-04', 'Shipped'),
 ('Andy', 'Fixter', '10174', '2003-11-06', 'Shipped'),
 ('Andy', 'Fixter', '10193', '2003-11-21', 'Shipped'),
 ('Andy', 'Fixter', '10223', '2004-02-20', 'Shipped'),
 ('Andy', 'Fixter', '10265', '2004-07-02', 'Shipped'),
 ('Andy', 'Fixter', '10270', '2004-07-19', 'Shipped'),
 ('Andy', 'Fixter', '10342', '2004-11-24', 'Shipped'),
 ('Andy', 'Fixter', '10347', '2004-11-29', 'Shipped'),
 ('Andy', 'Fixter', '10361', '2004-12-17', 'Shipped'),
 ('Andy', 'Fixter', '10370', '2005-01-20', 'Shipped'),
 ('Andy', 'Fixter', '10374', '2005-02-02', 'Shipped'),
 ('Andy', 'Fixter', '10391', '2005-03-09', 'Shipped'),
 ('Andy', 'Fixter', '10415', '2005-05-09', 'Disputed'),
 ('Andy', 'Fixter', '10420', '2005-05-29', 'In Process'),
 ('Barry', 'Jones', '10101', '2003-01-09', 'Shipped'),
 ('Barry', 'Jones', '10103', '2003-01-29', 'Shipped'),
 ('Barry', 'Jones', '10112', '2003-03-24', 'Shipped'),
 ('Barry', 'Jones', '10158', '2003-10-10', 'Shipped'),
 ('Barry', 'Jones', '10167', '2003-10-23', 'Cancelled'),
 ('Barry', 'Jones', '10181', '2003-11-12', 'Shipped'),
 ('Barry', 'Jones', '10188', '2003-11-18', 'Shipped'),
 ('Barry', 'Jones', '10191', '2003-11-20', 'Shipped'),
 ('Barry', 'Jones', '10220', '2004-02-12', 'Shipped'),
 ('Barry', 'Jones', '10230', '2004-03-15', 'Shipped'),
 ('Barry', 'Jones', '10284', '2004-08-21', 'Shipped'),
 ('Barry', 'Jones', '10289', '2004-09-03', 'Shipped'),
 ('Barry', 'Jones', '10291', '2004-09-08', 'Shipped'),
 ('Barry', 'Jones', '10296', '2004-09-15', 'Shipped'),
 ('Barry', 'Jones', '10297', '2004-09-16', 'Shipped'),
 ('Barry', 'Jones', '10300', '2003-10-04', 'Shipped'),
 ('Barry', 'Jones', '10301', '2003-10-05', 'Shipped'),
 ('Barry', 'Jones', '10309', '2004-10-15', 'Shipped'),
 ('Barry', 'Jones', '10310', '2004-10-16', 'Shipped'),
 ('Barry', 'Jones', '10320', '2004-11-03', 'Shipped'),
 ('Barry', 'Jones', '10323', '2004-11-05', 'Shipped'),
 ('Barry', 'Jones', '10325', '2004-11-05', 'Shipped'),
 ('Barry', 'Jones', '10326', '2004-11-09', 'Shipped'),
 ('Barry', 'Jones', '10334', '2004-11-19', 'On Hold'),
 ('Barry', 'Jones', '10389', '2005-03-03', 'Shipped'),
 ('Foon Yue', 'Tseng', '10102', '2003-01-10', 'Shipped'),
 ('Foon Yue', 'Tseng', '10115', '2003-04-04', 'Shipped'),
 ('Foon Yue', 'Tseng', '10127', '2003-06-03', 'Shipped'),
 ('Foon Yue', 'Tseng', '10163', '2003-10-20', 'Shipped'),
 ('Foon Yue', 'Tseng', '10171', '2003-11-05', 'Shipped'),
 ('Foon Yue', 'Tseng', '10196', '2003-11-26', 'Shipped'),
 ('Foon Yue', 'Tseng', '10204', '2003-12-02', 'Shipped'),
 ('Foon Yue', 'Tseng', '10237', '2004-04-05', 'Shipped'),
 ('Foon Yue', 'Tseng', '10242', '2004-04-20', 'Shipped'),
 ('Foon Yue', 'Tseng', '10245', '2004-05-04', 'Shipped'),
 ('Foon Yue', 'Tseng', '10261', '2004-06-17', 'Shipped'),
 ('Foon Yue', 'Tseng', '10267', '2004-07-07', 'Shipped'),
 ('Foon Yue', 'Tseng', '10319', '2004-11-03', 'Shipped'),
 ('Foon Yue', 'Tseng', '10324', '2004-11-05', 'Shipped'),
 ('Foon Yue', 'Tseng', '10337', '2004-11-21', 'Shipped'),
 ('Foon Yue', 'Tseng', '10349', '2004-12-01', 'Shipped'),
 ('Foon Yue', 'Tseng', '10411', '2005-05-01', 'Shipped'),
 ('George', 'Vanauf', '10107', '2003-02-24', 'Shipped'),
 ('George', 'Vanauf', '10109', '2003-03-10', 'Shipped'),
 ('George', 'Vanauf', '10131', '2003-06-16', 'Shipped'),
 ('George', 'Vanauf', '10146', '2003-09-03', 'Shipped'),
 ('George', 'Vanauf', '10172', '2003-11-05', 'Shipped'),
 ('George', 'Vanauf', '10195', '2003-11-25', 'Shipped'),
 ('George', 'Vanauf', '10206', '2003-12-05', 'Shipped'),
 ('George', 'Vanauf', '10233', '2004-03-29', 'Shipped'),
 ('George', 'Vanauf', '10235', '2004-04-02', 'Shipped'),
 ('George', 'Vanauf', '10236', '2004-04-03', 'Shipped'),
 ('George', 'Vanauf', '10248', '2004-05-07', 'Cancelled'),
 ('George', 'Vanauf', '10251', '2004-05-18', 'Shipped'),
 ('George', 'Vanauf', '10263', '2004-06-28', 'Shipped'),
 ('George', 'Vanauf', '10283', '2004-08-20', 'Shipped'),
 ('George', 'Vanauf', '10292', '2004-09-08', 'Shipped'),
 ('George', 'Vanauf', '10308', '2004-10-15', 'Shipped'),
 ('George', 'Vanauf', '10313', '2004-10-22', 'Shipped'),
 ('George', 'Vanauf', '10329', '2004-11-15', 'Shipped'),
 ('George', 'Vanauf', '10331', '2004-11-17', 'Shipped'),
 ('George', 'Vanauf', '10353', '2004-12-04', 'Shipped'),
 ('George', 'Vanauf', '10401', '2005-04-03', 'On Hold'),
 ('George', 'Vanauf', '10413', '2005-05-05', 'Shipped'),
 ('Gerard', 'Hernandez', '10104', '2003-01-31', 'Shipped'),
 ('Gerard', 'Hernandez', '10123', '2003-05-20', 'Shipped'),
 ('Gerard', 'Hernandez', '10128', '2003-06-06', 'Shipped'),
 ('Gerard', 'Hernandez', '10133', '2003-06-27', 'Shipped'),
 ('Gerard', 'Hernandez', '10136', '2003-07-04', 'Shipped'),
 ('Gerard', 'Hernandez', '10153', '2003-09-28', 'Shipped'),
 ('Gerard', 'Hernandez', '10156', '2003-10-08', 'Shipped'),
 ('Gerard', 'Hernandez', '10178', '2003-11-08', 'Shipped'),
 ('Gerard', 'Hernandez', '10180', '2003-11-11', 'Shipped'),
 ('Gerard', 'Hernandez', '10190', '2003-11-19', 'Shipped'),
 ('Gerard', 'Hernandez', '10203', '2003-12-02', 'Shipped'),
 ('Gerard', 'Hernandez', '10205', '2003-12-03', 'Shipped'),
 ('Gerard', 'Hernandez', '10212', '2004-01-16', 'Shipped'),
 ('Gerard', 'Hernandez', '10216', '2004-02-02', 'Shipped'),
 ('Gerard', 'Hernandez', '10224', '2004-02-21', 'Shipped'),
 ('Gerard', 'Hernandez', '10241', '2004-04-13', 'Shipped'),
 ('Gerard', 'Hernandez', '10244', '2004-04-29', 'Shipped'),
 ('Gerard', 'Hernandez', '10246', '2004-05-05', 'Shipped'),
 ('Gerard', 'Hernandez', '10255', '2004-06-04', 'Shipped'),
 ('Gerard', 'Hernandez', '10262', '2004-06-24', 'Cancelled'),
 ('Gerard', 'Hernandez', '10275', '2004-07-23', 'Shipped'),
 ('Gerard', 'Hernandez', '10279', '2004-08-09', 'Shipped'),
 ('Gerard', 'Hernandez', '10298', '2004-09-27', 'Shipped'),
 ('Gerard', 'Hernandez', '10304', '2004-10-11', 'Shipped'),
 ('Gerard', 'Hernandez', '10311', '2004-10-16', 'Shipped'),
 ('Gerard', 'Hernandez', '10315', '2004-10-29', 'Shipped'),
 ('Gerard', 'Hernandez', '10345', '2004-11-25', 'Shipped'),
 ('Gerard', 'Hernandez', '10350', '2004-12-02', 'Shipped'),
 ('Gerard', 'Hernandez', '10355', '2004-12-07', 'Shipped'),
 ('Gerard', 'Hernandez', '10358', '2004-12-10', 'Shipped'),
 ('Gerard', 'Hernandez', '10375', '2005-02-03', 'Shipped'),
 ('Gerard', 'Hernandez', '10378', '2005-02-10', 'Shipped'),
 ('Gerard', 'Hernandez', '10379', '2005-02-10', 'Shipped'),
 ('Gerard', 'Hernandez', '10380', '2005-02-16', 'Shipped'),
 ('Gerard', 'Hernandez', '10383', '2005-02-22', 'Shipped'),
 ('Gerard', 'Hernandez', '10386', '2005-03-01', 'Resolved'),
 ('Gerard', 'Hernandez', '10394', '2005-03-15', 'Shipped'),
 ('Gerard', 'Hernandez', '10397', '2005-03-28', 'Shipped'),
 ('Gerard', 'Hernandez', '10405', '2005-04-14', 'Shipped'),
 ('Gerard', 'Hernandez', '10412', '2005-05-03', 'Shipped'),
 ('Gerard', 'Hernandez', '10417', '2005-05-13', 'Disputed'),
 ('Gerard', 'Hernandez', '10424', '2005-05-31', 'In Process'),
 ('Gerard', 'Hernandez', '10425', '2005-05-31', 'In Process'),
 ('Julie', 'Firrelli', '10143', '2003-08-10', 'Shipped'),
 ('Julie', 'Firrelli', '10147', '2003-09-05', 'Shipped'),
 ('Julie', 'Firrelli', '10183', '2003-11-13', 'Shipped'),
 ('Julie', 'Firrelli', '10185', '2003-11-14', 'Shipped'),
 ('Julie', 'Firrelli', '10207', '2003-12-09', 'Shipped'),
 ('Julie', 'Firrelli', '10228', '2004-03-10', 'Shipped'),
 ('Julie', 'Firrelli', '10243', '2004-04-26', 'Shipped'),
 ('Julie', 'Firrelli', '10249', '2004-05-08', 'Shipped'),
 ('Julie', 'Firrelli', '10274', '2004-07-21', 'Shipped'),
 ('Julie', 'Firrelli', '10276', '2004-08-02', 'Shipped'),
 ('Julie', 'Firrelli', '10294', '2004-09-10', 'Shipped'),
 ('Julie', 'Firrelli', '10307', '2004-10-14', 'Shipped'),
 ('Julie', 'Firrelli', '10365', '2005-01-07', 'Shipped'),
 ('Julie', 'Firrelli', '10369', '2005-01-20', 'Shipped'),
 ('Larry', 'Bott', '10110', '2003-03-18', 'Shipped'),
 ('Larry', 'Bott', '10129', '2003-06-12', 'Shipped'),
 ('Larry', 'Bott', '10141', '2003-08-01', 'Shipped'),
 ('Larry', 'Bott', '10151', '2003-09-21', 'Shipped'),
 ('Larry', 'Bott', '10155', '2003-10-06', 'Shipped'),
 ('Larry', 'Bott', '10175', '2003-11-06', 'Shipped'),
 ('Larry', 'Bott', '10186', '2003-11-14', 'Shipped'),
 ('Larry', 'Bott', '10213', '2004-01-22', 'Shipped'),
 ('Larry', 'Bott', '10232', '2004-03-20', 'Shipped'),
 ('Larry', 'Bott', '10239', '2004-04-12', 'Shipped'),
 ('Larry', 'Bott', '10247', '2004-05-05', 'Shipped'),
 ('Larry', 'Bott', '10253', '2004-06-01', 'Cancelled'),
 ('Larry', 'Bott', '10299', '2004-09-30', 'Shipped'),
 ('Larry', 'Bott', '10302', '2003-10-06', 'Shipped'),
 ('Larry', 'Bott', '10306', '2004-10-14', 'Shipped'),
 ('Larry', 'Bott', '10316', '2004-11-01', 'Shipped'),
 ('Larry', 'Bott', '10332', '2004-11-17', 'Shipped'),
 ('Larry', 'Bott', '10351', '2004-12-03', 'Shipped'),
 ('Larry', 'Bott', '10363', '2005-01-06', 'Shipped'),
 ('Larry', 'Bott', '10373', '2005-01-31', 'Shipped'),
 ('Larry', 'Bott', '10377', '2005-02-09', 'Shipped'),
 ('Larry', 'Bott', '10403', '2005-04-08', 'Shipped'),
 ('Leslie', 'Jennings', '10111', '2003-03-25', 'Shipped'),
 ('Leslie', 'Jennings', '10113', '2003-03-26', 'Shipped'),
 ('Leslie', 'Jennings', '10135', '2003-07-02', 'Shipped'),
 ('Leslie', 'Jennings', '10140', '2003-07-24', 'Shipped'),
 ('Leslie', 'Jennings', '10142', '2003-08-08', 'Shipped'),
 ('Leslie', 'Jennings', '10149', '2003-09-12', 'Shipped'),
 ('Leslie', 'Jennings', '10159', '2003-10-10', 'Shipped'),
 ('Leslie', 'Jennings', '10162', '2003-10-18', 'Shipped'),
 ('Leslie', 'Jennings', '10168', '2003-10-28', 'Shipped'),
 ('Leslie', 'Jennings', '10182', '2003-11-12', 'Shipped'),
 ('Leslie', 'Jennings', '10201', '2003-12-01', 'Shipped'),
 ('Leslie', 'Jennings', '10219', '2004-02-10', 'Shipped'),
 ('Leslie', 'Jennings', '10229', '2004-03-11', 'Shipped'),
 ('Leslie', 'Jennings', '10250', '2004-05-11', 'Shipped'),
 ('Leslie', 'Jennings', '10257', '2004-06-14', 'Shipped'),
 ('Leslie', 'Jennings', '10271', '2004-07-20', 'Shipped'),
 ('Leslie', 'Jennings', '10282', '2004-08-20', 'Shipped'),
 ('Leslie', 'Jennings', '10312', '2004-10-21', 'Shipped'),
 ('Leslie', 'Jennings', '10317', '2004-11-02', 'Shipped'),
 ('Leslie', 'Jennings', '10333', '2004-11-18', 'Shipped'),
 ('Leslie', 'Jennings', '10335', '2004-11-19', 'Shipped'),
 ('Leslie', 'Jennings', '10357', '2004-12-10', 'Shipped'),
 ('Leslie', 'Jennings', '10362', '2005-01-05', 'Shipped'),
 ('Leslie', 'Jennings', '10368', '2005-01-19', 'Shipped'),
 ('Leslie', 'Jennings', '10371', '2005-01-23', 'Shipped'),
 ('Leslie', 'Jennings', '10381', '2005-02-17', 'Shipped'),
 ('Leslie', 'Jennings', '10382', '2005-02-17', 'Shipped'),
 ('Leslie', 'Jennings', '10384', '2005-02-23', 'Shipped'),
 ('Leslie', 'Jennings', '10385', '2005-02-28', 'Shipped'),
 ('Leslie', 'Jennings', '10390', '2005-03-04', 'Shipped'),
 ('Leslie', 'Jennings', '10396', '2005-03-23', 'Shipped'),
 ('Leslie', 'Jennings', '10400', '2005-04-01', 'Shipped'),
 ('Leslie', 'Jennings', '10407', '2005-04-22', 'On Hold'),
 ('Leslie', 'Jennings', '10421', '2005-05-29', 'In Process'),
 ('Leslie', 'Thompson', '10124', '2003-05-21', 'Shipped'),
 ('Leslie', 'Thompson', '10145', '2003-08-25', 'Shipped'),
 ('Leslie', 'Thompson', '10154', '2003-10-02', 'Shipped'),
 ('Leslie', 'Thompson', '10160', '2003-10-11', 'Shipped'),
 ('Leslie', 'Thompson', '10189', '2003-11-18', 'Shipped'),
 ('Leslie', 'Thompson', '10199', '2003-12-01', 'Shipped'),
 ('Leslie', 'Thompson', '10209', '2004-01-09', 'Shipped'),
 ('Leslie', 'Thompson', '10215', '2004-01-29', 'Shipped'),
 ('Leslie', 'Thompson', '10222', '2004-02-19', 'Shipped'),
 ('Leslie', 'Thompson', '10226', '2004-02-26', 'Shipped'),
 ('Leslie', 'Thompson', '10278', '2004-08-06', 'Shipped'),
 ('Leslie', 'Thompson', '10346', '2004-11-29', 'Shipped'),
 ('Leslie', 'Thompson', '10367', '2005-01-12', 'Resolved'),
 ('Leslie', 'Thompson', '10376', '2005-02-08', 'Shipped'),
 ('Loui', 'Bondur', '10114', '2003-04-01', 'Shipped'),
 ('Loui', 'Bondur', '10121', '2003-05-07', 'Shipped'),
 ('Loui', 'Bondur', '10122', '2003-05-08', 'Shipped'),
 ('Loui', 'Bondur', '10134', '2003-07-01', 'Shipped'),
 ('Loui', 'Bondur', '10137', '2003-07-10', 'Shipped'),
 ('Loui', 'Bondur', '10194', '2003-11-25', 'Shipped'),
 ('Loui', 'Bondur', '10208', '2004-01-02', 'Shipped'),
 ('Loui', 'Bondur', '10211', '2004-01-15', 'Shipped'),
 ('Loui', 'Bondur', '10227', '2004-03-02', 'Shipped'),
 ('Loui', 'Bondur', '10252', '2004-05-26', 'Shipped'),
 ('Loui', 'Bondur', '10286', '2004-08-28', 'Shipped'),
 ('Loui', 'Bondur', '10336', '2004-11-20', 'Shipped'),
 ('Loui', 'Bondur', '10343', '2004-11-24', 'Shipped'),
 ('Loui', 'Bondur', '10344', '2004-11-25', 'Shipped'),
 ('Loui', 'Bondur', '10356', '2004-12-09', 'Shipped'),
 ('Loui', 'Bondur', '10359', '2004-12-15', 'Shipped'),
 ('Loui', 'Bondur', '10364', '2005-01-06', 'Shipped'),
 ('Loui', 'Bondur', '10395', '2005-03-17', 'Shipped'),
 ('Loui', 'Bondur', '10398', '2005-03-30', 'Shipped'),
 ('Loui', 'Bondur', '10402', '2005-04-07', 'Shipped'),
 ('Mami', 'Nishi', '10108', '2003-03-03', 'Shipped'),
 ('Mami', 'Nishi', '10117', '2003-04-16', 'Shipped'),
 ('Mami', 'Nishi', '10150', '2003-09-19', 'Shipped'),
 ('Mami', 'Nishi', '10165', '2003-10-22', 'Shipped'),
 ('Mami', 'Nishi', '10187', '2003-11-15', 'Shipped'),
 ('Mami', 'Nishi', '10198', '2003-11-27', 'Shipped'),
 ('Mami', 'Nishi', '10200', '2003-12-01', 'Shipped'),
 ('Mami', 'Nishi', '10210', '2004-01-12', 'Shipped'),
 ('Mami', 'Nishi', '10240', '2004-04-13', 'Shipped'),
 ('Mami', 'Nishi', '10258', '2004-06-15', 'Shipped'),
 ('Mami', 'Nishi', '10277', '2004-08-04', 'Shipped'),
 ('Mami', 'Nishi', '10330', '2004-11-16', 'Shipped'),
 ('Mami', 'Nishi', '10339', '2004-11-23', 'Shipped'),
 ('Mami', 'Nishi', '10372', '2005-01-26', 'Shipped'),
 ('Mami', 'Nishi', '10387', '2005-03-02', 'Shipped'),
 ('Mami', 'Nishi', '10408', '2005-04-22', 'Shipped'),
 ('Martin', 'Gerard', '10118', '2003-04-21', 'Shipped'),
 ('Martin', 'Gerard', '10126', '2003-05-28', 'Shipped'),
 ('Martin', 'Gerard', '10177', '2003-11-07', 'Shipped'),
 ('Martin', 'Gerard', '10184', '2003-11-14', 'Shipped'),
 ('Martin', 'Gerard', '10197', '2003-11-26', 'Shipped'),
 ('Martin', 'Gerard', '10214', '2004-01-26', 'Shipped'),
 ('Martin', 'Gerard', '10225', '2004-02-22', 'Shipped'),
 ('Martin', 'Gerard', '10231', '2004-03-19', 'Shipped'),
 ('Martin', 'Gerard', '10287', '2004-08-30', 'Shipped'),
 ('Martin', 'Gerard', '10303', '2004-10-06', 'Shipped'),
 ('Martin', 'Gerard', '10340', '2004-11-24', 'Shipped'),
 ('Martin', 'Gerard', '10348', '2004-11-01', 'Shipped'),
 ('Pamela', 'Castillo', '10105', '2003-02-11', 'Shipped'),
 ('Pamela', 'Castillo', '10106', '2003-02-17', 'Shipped'),
 ('Pamela', 'Castillo', '10116', '2003-04-11', 'Shipped'),
 ('Pamela', 'Castillo', '10119', '2003-04-28', 'Shipped'),
 ('Pamela', 'Castillo', '10144', '2003-08-13', 'Shipped'),
 ('Pamela', 'Castillo', '10157', '2003-10-09', 'Shipped'),
 ('Pamela', 'Castillo', '10161', '2003-10-17', 'Shipped'),
 ('Pamela', 'Castillo', '10164', '2003-10-21', 'Resolved'),
 ('Pamela', 'Castillo', '10170', '2003-11-04', 'Shipped'),
 ('Pamela', 'Castillo', '10173', '2003-11-05', 'Shipped'),
 ('Pamela', 'Castillo', '10176', '2003-11-06', 'Shipped'),
 ('Pamela', 'Castillo', '10218', '2004-02-09', 'Shipped'),
 ('Pamela', 'Castillo', '10221', '2004-02-18', 'Shipped'),
 ('Pamela', 'Castillo', '10238', '2004-04-09', 'Shipped'),
 ('Pamela', 'Castillo', '10256', '2004-06-08', 'Shipped'),
 ('Pamela', 'Castillo', '10266', '2004-07-06', 'Shipped'),
 ('Pamela', 'Castillo', '10269', '2004-07-16', 'Shipped'),
 ('Pamela', 'Castillo', '10273', '2004-07-21', 'Shipped'),
 ('Pamela', 'Castillo', '10280', '2004-08-17', 'Shipped'),
 ('Pamela', 'Castillo', '10293', '2004-09-09', 'Shipped'),
 ('Pamela', 'Castillo', '10314', '2004-10-22', 'Shipped'),
 ('Pamela', 'Castillo', '10327', '2004-11-10', 'Resolved'),
 ('Pamela', 'Castillo', '10328', '2004-11-12', 'Shipped'),
 ('Pamela', 'Castillo', '10338', '2004-11-22', 'Shipped'),
 ('Pamela', 'Castillo', '10341', '2004-11-24', 'Shipped'),
 ('Pamela', 'Castillo', '10366', '2005-01-10', 'Shipped'),
 ('Pamela', 'Castillo', '10392', '2005-03-10', 'Shipped'),
 ('Pamela', 'Castillo', '10406', '2005-04-15', 'Disputed'),
 ('Pamela', 'Castillo', '10416', '2005-05-10', 'Shipped'),
 ('Pamela', 'Castillo', '10419', '2005-05-17', 'Shipped'),
 ('Pamela', 'Castillo', '10423', '2005-05-30', 'In Process'),
 ('Peter', 'Marsh', '10132', '2003-06-25', 'Shipped'),
 ('Peter', 'Marsh', '10138', '2003-07-07', 'Shipped'),
 ('Peter', 'Marsh', '10179', '2003-11-11', 'Cancelled'),
 ('Peter', 'Marsh', '10202', '2003-12-02', 'Shipped'),
 ('Peter', 'Marsh', '10217', '2004-02-04', 'Shipped'),
 ('Peter', 'Marsh', '10234', '2004-03-30', 'Shipped'),
 ('Peter', 'Marsh', '10254', '2004-06-03', 'Shipped'),
 ('Peter', 'Marsh', '10259', '2004-06-15', 'Shipped'),
 ('Peter', 'Marsh', '10260', '2004-06-16', 'Cancelled'),
 ('Peter', 'Marsh', '10268', '2004-07-12', 'Shipped'),
 ('Peter', 'Marsh', '10288', '2004-09-01', 'Shipped'),
 ('Peter', 'Marsh', '10354', '2004-12-04', 'Shipped'),
 ('Peter', 'Marsh', '10360', '2004-12-16', 'Shipped'),
 ('Peter', 'Marsh', '10393', '2005-03-11', 'Shipped'),
 ('Peter', 'Marsh', '10399', '2005-04-01', 'Shipped'),
 ('Peter', 'Marsh', '10404', '2005-04-08', 'Shipped'),
 ('Peter', 'Marsh', '10409', '2005-04-23', 'Shipped'),
 ('Peter', 'Marsh', '10410', '2005-04-29', 'Shipped'),
 ('Peter', 'Marsh', '10418', '2005-05-16', 'Shipped'),
 ('Steve', 'Patterson', '10100', '2003-01-06', 'Shipped'),
 ('Steve', 'Patterson', '10130', '2003-06-16', 'Shipped'),
 ('Steve', 'Patterson', '10166', '2003-10-21', 'Shipped'),
 ('Steve', 'Patterson', '10192', '2003-11-20', 'Shipped'),
 ('Steve', 'Patterson', '10264', '2004-06-30', 'Shipped'),
 ('Steve', 'Patterson', '10272', '2004-07-20', 'Shipped'),
 ('Steve', 'Patterson', '10281', '2004-08-19', 'Shipped'),
 ('Steve', 'Patterson', '10285', '2004-08-27', 'Shipped'),
 ('Steve', 'Patterson', '10290', '2004-09-07', 'Shipped'),
 ('Steve', 'Patterson', '10295', '2004-09-10', 'Shipped'),
 ('Steve', 'Patterson', '10305', '2004-10-13', 'Shipped'),
 ('Steve', 'Patterson', '10318', '2004-11-02', 'Shipped'),
 ('Steve', 'Patterson', '10321', '2004-11-04', 'Shipped'),
 ('Steve', 'Patterson', '10322', '2004-11-04', 'Shipped'),
 ('Steve', 'Patterson', '10352', '2004-12-03', 'Shipped'),
 ('Steve', 'Patterson', '10388', '2005-03-03', 'Shipped'),
 ('Steve', 'Patterson', '10414', '2005-05-06', 'On Hold'),
 ('Steve', 'Patterson', '10422', '2005-05-30', 'In Process')]

## Customers and their Payments (another One-to-Many join)

Return a list of customers first and last names along with details about their payments including the amount and date of payments. Sort these results in descending order by the payment amount.

In [14]:
c = conn.cursor()
sql_str = """

SELECT payments.amount, employees.firstName, employees.lastName, payments.paymentDate, payments.checkNumber
FROM employees
JOIN customers
ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN payments
ON customers.customerNumber = payments.customerNumber
ORDER BY payments.amount DESC, employees.firstName, employees.lastName, payments.paymentDate, payments.checkNumber;


"""

c.execute(sql_str).fetchall()

[('9977.85', 'Steve', 'Patterson', '2003-11-08', 'GC60330'),
 ('9821.32', 'Andy', 'Fixter', '2003-10-17', 'JK479662'),
 ('9658.74', 'Steve', 'Patterson', '2004-12-06', 'FI192930'),
 ('9415.13', 'Andy', 'Fixter', '2004-07-28', 'AB661578'),
 ('8807.12', 'Pamela', 'Castillo', '2005-05-03', 'HG635467'),
 ('85559.12', 'Leslie', 'Jennings', '2003-11-03', 'DJ15149'),
 ('85410.87', 'Leslie', 'Jennings', '2004-08-28', 'BG255406'),
 ('85024.46', 'Barry', 'Jones', '2003-12-03', 'GN228846'),
 ('83598.04', 'Leslie', 'Jennings', '2005-04-16', 'ET64396'),
 ('8307.28', 'Julie', 'Firrelli', '2005-01-18', 'GJ597719'),
 ('82261.22', 'Andy', 'Fixter', '2004-12-15', 'MA765515'),
 ('80375.24', 'Leslie', 'Thompson', '2004-03-15', 'NQ865547'),
 ('7678.25', 'Leslie', 'Thompson', '2003-12-09', 'JP113227'),
 ('7674.94', 'Barry', 'Jones', '2003-04-09', 'LA685678'),
 ('7612.06', 'Pamela', 'Castillo', '2004-02-17', 'LL427009'),
 ('7565.08', 'Andy', 'Fixter', '2003-05-31', 'NP603840'),
 ('75020.13', 'Peter', 'Marsh', '2005-05-23', 'AL493079'),
 ('7466.32', 'Barry', 'Jones', '2004-11-18', 'IP383901'),
 ('7310.42', 'Larry', 'Bott', '2004-01-31', 'PO860906'),
 ('7178.66', 'George', 'Vanauf', '2004-04-16', 'EN930356'),
 ('6631.36', 'George', 'Vanauf', '2003-09-15', 'AO757239'),
 ('65071.26', 'Gerard', 'Hernandez', '2005-03-25', 'IN446258'),
 ('6419.84', 'Pamela', 'Castillo', '2004-08-01', 'CT821147'),
 ('63843.55', 'Gerard', 'Hernandez', '2003-12-09', 'KT52578'),
 ('63357.13', 'Steve', 'Patterson', '2004-09-07', 'NN711988'),
 ('6276.60', 'Julie', 'Firrelli', '2004-05-14', 'FN155234'),
 ('615.45', 'Mami', 'Nishi', '2005-05-18', 'JPMR4544'),
 ('61402.00', 'Martin', 'Gerard', '2004-09-18', 'LF501133'),
 ('61234.67', 'Barry', 'Jones', '2004-11-06', 'EU280955'),
 ('6066.78', 'Gerard', 'Hernandez', '2004-10-19', 'HQ336336'),
 ('6036.96', 'Steve', 'Patterson', '2003-07-06', 'HQ920205'),
 ('59830.55', 'Gerard', 'Hernandez', '2004-01-30', 'HJ32686'),
 ('59551.38', 'Leslie', 'Jennings', '2004-06-21', 'EF485824'),
 ('59265.14', 'Julie', 'Firrelli', '2003-12-26', 'BH167026'),
 ('5899.38', 'George', 'Vanauf', '2004-04-14', 'BL66528'),
 ('58841.35', 'Foon Yue', 'Tseng', '2003-06-18', 'IP568906'),
 ('58793.53', 'Foon Yue', 'Tseng', '2003-12-22', 'BF686658'),
 ('5858.56', 'Steve', 'Patterson', '2004-09-21', 'IS946883'),
 ('5759.42', 'Gerard', 'Hernandez', '2004-02-10', 'EP227123'),
 ('57131.92', 'Martin', 'Gerard', '2003-06-13', 'OO606861'),
 ('55639.66', 'Leslie', 'Jennings', '2004-11-02', 'HR86578'),
 ('55425.77', 'Steve', 'Patterson', '2003-12-05', 'PN238558'),
 ('5494.78', 'Foon Yue', 'Tseng', '2003-01-30', 'GQ132144'),
 ('53959.21', 'Pamela', 'Castillo', '2003-02-20', 'JJ246391'),
 ('53745.34', 'Pamela', 'Castillo', '2004-11-02', 'NU21326'),
 ('53116.99', 'Gerard', 'Hernandez', '2004-10-22', 'HE84936'),
 ('52825.29', 'Larry', 'Bott', '2004-11-03', 'AM968797'),
 ('52548.49', 'Julie', 'Firrelli', '2003-11-24', 'MU817160'),
 ('52166.00', 'Peter', 'Marsh', '2004-12-31', 'MN89921'),
 ('52151.81', 'Pamela', 'Castillo', '2003-03-02', 'GP636783'),
 ('51619.02', 'Pamela', 'Castillo', '2004-07-18', 'HG438769'),
 ('51209.58', 'Loui', 'Bondur', '2004-12-04', 'CE51751'),
 ('51152.86', 'Julie', 'Firrelli', '2004-08-13', 'GC697638'),
 ('51001.22', 'Mami', 'Nishi', '2003-03-09', 'EK785462'),
 ('50824.66', 'Loui', 'Bondur', '2003-05-25', 'CI471510'),
 ('50799.69', 'Steve', 'Patterson', '2004-11-17', 'HL575273'),
 ('50743.65', 'Leslie', 'Jennings', '2003-11-18', 'BR478494'),
 ('50342.74', 'Leslie', 'Thompson', '2003-09-05', 'LL562733'),
 ('50218.95', 'Barry', 'Jones', '2003-02-16', 'DB889831'),
 ('50025.35', 'George', 'Vanauf', '2004-12-02', 'MA724562'),
 ('49705.52', 'Loui', 'Bondur', '2005-01-10', 'CO351193'),
 ('49614.72', 'Loui', 'Bondur', '2004-01-16', 'FU793410'),
 ('49539.37', 'Gerard', 'Hernandez', '2003-10-26', 'JN355280'),
 ('49523.67', 'Gerard', 'Hernandez', '2005-02-22', 'NG94694'),
 ('49165.16', 'Loui', 'Bondur', '2004-01-28', 'HJ217687'),
 ('48927.64', 'Mami', 'Nishi', '2004-11-29', 'KB54275'),
 ('48809.90', 'Barry', 'Jones', '2004-09-30', 'KR822727'),
 ('48425.69', 'Larry', 'Bott', '2003-03-27', 'KL124726'),
 ('48355.87', 'Steve', 'Patterson', '2004-11-27', 'PE176846'),
 ('48298.99', 'Pamela', 'Castillo', '2004-09-04', 'NE404084'),
 ('47924.19', 'Gerard', 'Hernandez', '2004-08-08', 'LN373447'),
 ('47513.19', 'Martin', 'Gerard', '2003-11-29', 'JH546765'),
 ('47411.33', 'Steve', 'Patterson', '2004-10-28', 'DR578578'),
 ('47375.92', 'Martin', 'Gerard', '2004-03-13', 'AJ574927'),
 ('47177.59', 'Mami', 'Nishi', '2004-01-19', 'CI381435'),
 ('47159.11', 'Larry', 'Bott', '2004-12-08', 'BQ39062'),
 ('47142.70', 'Leslie', 'Jennings', '2004-12-27', 'HI366474'),
 ('4710.73', 'Pamela', 'Castillo', '2004-07-03', 'CN328545'),
 ('46895.48', 'Gerard', 'Hernandez', '2005-05-19', 'DL460618'),
 ('46788.14', 'Larry', 'Bott', '2004-11-16', 'IF245157'),
 ('46781.66', 'Leslie', 'Jennings', '2005-03-15', 'LA556321'),
 ('46770.52', 'Larry', 'Bott', '2005-02-15', 'DG336041'),
 ('46656.94', 'Loui', 'Bondur', '2005-06-09', 'HJ618252'),
 ('4632.31', 'Gerard', 'Hernandez', '2004-06-21', 'ED520529'),
 ('45994.07', 'George', 'Vanauf', '2004-11-23', 'HS86661'),
 ('45864.03', 'Andy', 'Fixter', '2003-05-20', 'GG31455'),
 ('45785.34', 'Larry', 'Bott', '2005-01-27', 'CS435306'),
 ('45480.79', 'Mami', 'Nishi', '2003-12-09', 'BJ535230'),
 ('45352.47', 'Pamela', 'Castillo', '2004-08-09', 'LQ244073'),
 ('45084.38', 'Leslie', 'Jennings', '2003-11-25', 'NT141748'),
 ('44894.74', 'Andy', 'Fixter', '2004-03-10', 'NR27552'),
 ('4465.85', 'Leslie', 'Thompson', '2003-10-18', 'BR941480'),
 ('44400.50', 'Foon Yue', 'Tseng', '2004-11-16', 'OH367219'),
 ('44380.15', 'Mami', 'Nishi', '2003-04-22', 'BI507030'),
 ('4424.40', 'Julie', 'Firrelli', '2004-09-24', 'IS150005'),
 ('44160.92', 'Peter', 'Marsh', '2004-07-07', 'DC979307'),
 ('43369.30', 'Leslie', 'Jennings', '2004-03-26', 'LF217299'),
 ('43134.04', 'Steve', 'Patterson', '2004-09-05', 'KH910279'),
 ('42813.83', 'Pamela', 'Castillo', '2004-11-27', 'PH29054'),
 ('42783.81', 'Gerard', 'Hernandez', '2003-11-22', 'IL104425'),
 ('42339.76', 'George', 'Vanauf', '2004-11-06', 'HL685576'),
 ('42044.77', 'George', 'Vanauf', '2004-07-10', 'PI15215'),
 ('41554.73', 'Andy', 'Fixter', '2003-09-28', 'LE432182'),
 ('41016.75', 'Julie', 'Firrelli', '2003-08-20', 'HO576374'),
 ('40978.53', 'Loui', 'Bondur', '2004-03-18', 'FP549817'),
 ('40473.86', 'Martin', 'Gerard', '2003-12-14', 'MM342086'),
 ('40206.20', 'Gerard', 'Hernandez', '2003-02-25', 'JN722010'),
 ('39964.63', 'Foon Yue', 'Tseng', '2004-12-14', 'KI884577'),
 ('39712.10', 'Loui', 'Bondur', '2003-12-10', 'LJ160635'),
 ('39580.60', 'Leslie', 'Thompson', '2005-02-06', 'NM739638'),
 ('39440.59', 'Peter', 'Marsh', '2004-12-24', 'PQ803830'),
 ('3879.96', 'Leslie', 'Thompson', '2003-12-04', 'GL756480'),
 ('38785.48', 'Peter', 'Marsh', '2004-09-16', 'BQ327613'),
 ('38675.13', 'Leslie', 'Jennings', '2003-08-05', 'NI908214'),
 ('38547.19', 'Andy', 'Fixter', '2003-11-13', 'KM841847'),
 ('38524.29', 'Pamela', 'Castillo', '2003-11-18', 'DO106109'),
 ('38139.18', 'Foon Yue', 'Tseng', '2003-12-05', 'HA777606'),
 ('37723.79', 'Pamela', 'Castillo', '2003-11-24', 'NI983021'),
 ('37654.09', 'Pamela', 'Castillo', '2004-12-05', 'BJ483870'),
 ('37602.48', 'Larry', 'Bott', '2003-10-27', 'AK412714'),
 ('37527.58', 'George', 'Vanauf', '2004-08-30', 'IO164641'),
 ('37455.77', 'Larry', 'Bott', '2003-11-23', 'HB150714'),
 ('37281.36', 'Peter', 'Marsh', '2004-06-24', 'ES347491'),
 ('37258.94', 'Larry', 'Bott', '2004-06-15', 'OO846801'),
 ('36798.88', 'Barry', 'Jones', '2003-10-24', 'AD304085'),
 ('36527.61', 'George', 'Vanauf', '2003-12-18', 'HI358554'),
 ('36442.34', 'Peter', 'Marsh', '2004-05-15', 'NB291497'),
 ('36251.03', 'Gerard', 'Hernandez', '2003-07-19', 'AU364101'),
 ('36164.46', 'Pamela', 'Castillo', '2003-10-31', 'MQ413968'),
 ('36140.38', 'Gerard', 'Hernandez', '2004-11-01', 'DB583216'),
 ('36092.40', 'George', 'Vanauf', '2003-12-07', 'OM548174'),
 ('36070.47', 'Leslie', 'Thompson', '2004-02-13', 'PB951268'),
 ('36069.26', 'Gerard', 'Hernandez', '2004-05-04', 'PH785937'),
 ('36005.71', 'Barry', 'Jones', '2004-12-12', 'IR846303'),
 ('35826.33', 'Pamela', 'Castillo', '2003-05-12', 'CC871084'),
 ('35806.73', 'Andy', 'Fixter', '2004-08-02', 'JT819493'),
 ('35505.63', 'Andy', 'Fixter', '2003-12-10', 'CO645196'),
 ('35420.74', 'Gerard', 'Hernandez', '2004-07-09', 'MC46946'),
 ('35321.97', 'George', 'Vanauf', '2004-09-11', 'NB445135'),
 ('3516.04', 'Mami', 'Nishi', '2005-03-27', 'ME497970'),
 ('35157.75', 'Gerard', 'Hernandez', '2005-05-03', 'BOAF82044'),
 ('35152.12', 'Steve', 'Patterson', '2004-11-19', 'HI618861'),
 ('35034.57', 'Peter', 'Marsh', '2004-07-25', 'GH197075'),
 ('3474.66', 'Martin', 'Gerard', '2004-10-26', 'GK294076'),
 ('34638.14', 'Barry', 'Jones', '2004-11-28', 'MA302151'),
 ('34606.28', 'Julie', 'Firrelli', '2003-11-28', 'DA98827'),
 ('3452.75', 'Leslie', 'Thompson', '2005-03-02', 'BN17870'),
 ('34341.08', 'Larry', 'Bott', '2004-10-21', 'KA602407'),
 ('33967.73', 'Mami', 'Nishi', '2005-02-14', 'AJ478695'),
 ('33924.24', 'Pamela', 'Castillo', '2004-09-19', 'IJ399820'),
 ('33820.62', 'Barry', 'Jones', '2004-03-24', 'FH668230'),
 ('33818.34', 'Gerard', 'Hernandez', '2003-11-22', 'AF40894'),
 ('33594.58', 'George', 'Vanauf', '2004-11-08', 'IQ627690'),
 ('33383.14', 'Loui', 'Bondur', '2003-04-20', 'EH208589'),
 ('33347.88', 'Leslie', 'Thompson', '2004-08-20', 'ND748579'),
 ('33145.56', 'Martin', 'Gerard', '2004-11-15', 'DD995006'),
 ('32723.04', 'Larry', 'Bott', '2003-10-06', 'FA728475'),
 ('32680.31', 'Julie', 'Firrelli', '2003-09-16', 'FR499138'),
 ('32641.98', 'Leslie', 'Thompson', '2003-06-06', 'HQ55022'),
 ('32538.74', 'Barry', 'Jones', '2004-03-01', 'NM916675'),
 ('32260.16', 'Barry', 'Jones', '2004-09-05', 'NR157385'),
 ('32239.47', 'Foon Yue', 'Tseng', '2004-05-12', 'IR662429'),
 ('32077.44', 'Peter', 'Marsh', '2003-07-16', 'MB342426'),
 ('31835.36', 'Andy', 'Fixter', '2005-01-03', 'OD327378'),
 ('31670.37', 'Peter', 'Marsh', '2004-04-14', 'PJ434867'),
 ('31428.21', 'Martin', 'Gerard', '2003-11-24', 'AF246722'),
 ('31310.09', 'Barry', 'Jones', '2004-09-28', 'ER54537'),
 ('31102.85', 'George', 'Vanauf', '2004-05-30', 'NR631421'),
 ('3101.40', 'Martin', 'Gerard', '2003-05-09', 'BG407567'),
 ('30293.77', 'Steve', 'Patterson', '2005-04-15', 'ED203908'),
 ('30253.75', 'Peter', 'Marsh', '2005-05-25', 'EU531600'),
 ('29997.09', 'Leslie', 'Jennings', '2003-09-28', 'AH612904'),
 ('29848.52', 'Andy', 'Fixter', '2005-04-30', 'OJ819725'),
 ('29716.86', 'Larry', 'Bott', '2003-08-16', 'HH517378'),
 ('29429.14', 'Larry', 'Bott', '2003-07-07', 'FP443161'),
 ('29284.42', 'George', 'Vanauf', '2004-04-24', 'NH776924'),
 ('29070.38', 'Foon Yue', 'Tseng', '2005-05-20', 'BOFA23232'),
 ('2880.00', 'Peter', 'Marsh', '2003-07-05', 'HG738664'),
 ('28500.78', 'George', 'Vanauf', '2005-05-19', 'CITI3434344'),
 ('28394.54', 'Larry', 'Bott', '2004-05-22', 'LF737277'),
 ('28322.83', 'Julie', 'Firrelli', '2005-02-12', 'CA762595'),
 ('28211.70', 'Pamela', 'Castillo', '2004-04-26', 'ED39322'),
 ('27988.47', 'Barry', 'Jones', '2003-12-07', 'GB361972'),
 ('27966.54', 'Barry', 'Jones', '2005-04-18', 'FS299615'),
 ('27550.51', 'Foon Yue', 'Tseng', '2004-11-13', 'GJ715659'),
 ('27121.90', 'Pamela', 'Castillo', '2003-11-15', 'ED473873'),
 ('27083.78', 'Andy', 'Fixter', '2005-02-09', 'EM979878'),
 ('26311.63', 'Loui', 'Bondur', '2004-12-30', 'HD284647'),
 ('26304.13', 'George', 'Vanauf', '2004-12-17', 'OU516561'),
 ('26248.78', 'Leslie', 'Jennings', '2004-12-08', 'DM826140'),
 ('26155.91', 'Gerard', 'Hernandez', '2004-05-17', 'NU627706'),
 ('2611.84', 'Mami', 'Nishi', '2004-08-11', 'DD635282'),
 ('25833.14', 'George', 'Vanauf', '2003-03-20', 'JB117768'),
 ('25505.98', 'Foon Yue', 'Tseng', '2004-12-07', 'KF480160'),
 ('25080.96', 'Loui', 'Bondur', '2004-06-17', 'NA197101'),
 ('24995.61', 'Larry', 'Bott', '2004-03-28', 'JO719695'),
 ('24945.21', 'Martin', 'Gerard', '2004-12-06', 'ML780814'),
 ('24879.08', 'George', 'Vanauf', '2003-11-19', 'IO448913'),
 ('2434.25', 'Leslie', 'Jennings', '2004-11-14', 'BR352384'),
 ('24101.81', 'Barry', 'Jones', '2003-10-18', 'FA465482'),
 ('24013.52', 'Andy', 'Fixter', '2003-08-03', 'IA793562'),
 ('23936.53', 'Andy', 'Fixter', '2003-11-15', 'HL209210'),
 ('23923.93', 'Leslie', 'Jennings', '2003-12-11', 'ID449593'),
 ('23908.24', 'Larry', 'Bott', '2003-10-20', 'DP677013'),
 ('23602.90', 'Larry', 'Bott', '2005-03-10', 'AE192287'),
 ('23419.47', 'Loui', 'Bondur', '2003-07-18', 'HN114306'),
 ('23333.06', 'Julie', 'Firrelli', '2004-10-24', 'AP286625'),
 ('22997.45', 'Foon Yue', 'Tseng', '2004-07-01', 'II180006'),
 ('22602.36', 'Foon Yue', 'Tseng', '2004-04-25', 'CM564612'),
 ('22474.17', 'Peter', 'Marsh', '2004-02-28', 'LA318629'),
 ('22292.62', 'George', 'Vanauf', '2003-03-12', 'CL442705'),
 ('22275.73', 'Larry', 'Bott', '2003-12-04', 'OC773849'),
 ('22162.61', 'Martin', 'Gerard', '2004-02-06', 'NA377824'),
 ('22042.37', 'Foon Yue', 'Tseng', '2003-10-31', 'OA595449'),
 ('22037.91', 'Mami', 'Nishi', '2004-06-21', 'DO787644'),
 ('21665.98', 'Foon Yue', 'Tseng', '2003-04-16', 'LM271923'),
 ('21432.31', 'Andy', 'Fixter', '2005-03-01', 'NF959653'),
 ('21053.69', 'Leslie', 'Thompson', '2004-01-18', 'DG700707'),
 ('20644.24', 'Mami', 'Nishi', '2003-12-02', 'BN347084'),
 ('20564.86', 'Pamela', 'Castillo', '2004-12-01', 'HR182688'),
 ('20452.50', 'Leslie', 'Thompson', '2003-10-24', 'LG808674'),
 ('20355.24', 'Julie', 'Firrelli', '2004-03-29', 'IG462397'),
 ('20314.44', 'Foon Yue', 'Tseng', '2004-07-26', 'GB852215'),
 ('20220.04', 'Peter', 'Marsh', '2003-12-16', 'AG240323'),
 ('20009.53', 'Gerard', 'Hernandez', '2004-08-16', 'MF629602'),
 ('1960.80', 'Loui', 'Bondur', '2004-09-09', 'AD832091'),
 ('19501.82', 'Gerard', 'Hernandez', '2004-11-14', 'DB933704'),
 ('18997.89', 'Gerard', 'Hernandez', '2004-03-15', 'GB878038'),
 ('18888.31', 'Loui', 'Bondur', '2004-12-11', 'BQ602907'),
 ('18473.71', 'Steve', 'Patterson', '2004-07-11', 'FP170292'),
 ('1834.56', 'Loui', 'Bondur', '2005-01-29', 'OB648482'),
 ('17928.09', 'Loui', 'Bondur', '2005-05-17', 'EQ12267'),
 ('17876.32', 'Barry', 'Jones', '2004-11-04', 'KI831359'),
 ('17746.26', 'Pamela', 'Castillo', '2003-10-27', 'PC688499'),
 ('17359.53', 'Barry', 'Jones', '2004-10-03', 'BO711618'),
 ('17032.29', 'George', 'Vanauf', '2003-06-25', 'ER615123'),
 ('16909.84', 'Foon Yue', 'Tseng', '2003-11-18', 'JG981190'),
 ('16901.38', 'Pamela', 'Castillo', '2004-03-03', 'MD809704'),
 ('1679.92', 'Foon Yue', 'Tseng', '2004-04-30', 'MO743231'),
 ('1676.14', 'Gerard', 'Hernandez', '2004-12-18', 'OM314933'),
 ('16700.47', 'Loui', 'Bondur', '2003-05-21', 'GT878649'),
 ('16537.85', 'Leslie', 'Jennings', '2003-04-09', 'PI42991'),
 ('1627.56', 'Pamela', 'Castillo', '2003-04-19', 'CC475233'),
 ('16212.59', 'Larry', 'Bott', '2004-04-25', 'NQ966143'),
 ('15822.84', 'Mami', 'Nishi', '2004-11-19', 'CP804873'),
 ('15322.93', 'Martin', 'Gerard', '2004-04-02', 'NJ906924'),
 ('15183.63', 'Mami', 'Nishi', '2004-04-17', 'AU750837'),
 ('15130.97', 'Pamela', 'Castillo', '2003-11-20', 'FN640986'),
 ('15059.76', 'Steve', 'Patterson', '2004-09-21', 'OG208861'),
 ('1491.38', 'Barry', 'Jones', '2003-10-28', 'FD317790'),
 ('14571.44', 'Gerard', 'Hernandez', '2003-06-05', 'JM555205'),
 ('14379.90', 'Pamela', 'Castillo', '2005-02-03', 'GB117430'),
 ('14232.70', 'Gerard', 'Hernandez', '2003-07-21', 'KI744716'),
 ('14191.12', 'Leslie', 'Thompson', '2004-12-17', 'BO864823'),
 ('13920.26', 'Loui', 'Bondur', '2003-07-21', 'ED878227'),
 ('13671.82', 'Larry', 'Bott', '2004-12-13', 'DQ409197'),
 ('12692.19', 'Leslie', 'Jennings', '2005-02-02', 'KG644125'),
 ('12573.28', 'Leslie', 'Jennings', '2004-02-29', 'PT550181'),
 ('12538.01', 'Barry', 'Jones', '2004-09-19', 'ED743615'),
 ('12530.51', 'Julie', 'Firrelli', '2004-08-02', 'GB890854'),
 ('12432.32', 'Gerard', 'Hernandez', '2005-06-03', 'HR224331'),
 ('12190.85', 'Loui', 'Bondur', '2005-04-23', 'BJMPR4545'),
 ('12081.52', 'Pamela', 'Castillo', '2004-12-03', 'BC726082'),
 ('120166.58', 'Gerard', 'Hernandez', '2005-03-18', 'JE105477'),
 ('11843.45', 'Julie', 'Firrelli', '2004-05-13', 'GP545698'),
 ('116208.40', 'Gerard', 'Hernandez', '2004-12-31', 'ID10962'),
 ('1128.20', 'Pamela', 'Castillo', '2003-08-22', 'MS154481'),
 ('111654.40', 'Leslie', 'Jennings', '2003-08-15', 'KI131716'),
 ('11044.30', 'Leslie', 'Jennings', '2003-04-11', 'CQ287967'),
 ('105743.00', 'Mami', 'Nishi', '2003-12-26', 'KM172879'),
 ('10549.01', 'Barry', 'Jones', '2003-01-28', 'DI925118'),
 ('10223.83', 'Steve', 'Patterson', '2003-01-16', 'IS232033'),
 ('101244.59', 'Leslie', 'Jennings', '2005-03-05', 'AE215433')]

## Orders, Order details and Product Details (a Many-to-Many Join)

Return a list of customer first and last names, product names, quantities, and date ordered for each of the customers and each of their orders. Sort these in descending order by the order date.

Note: This will require joining 4 tables! This can be tricky! Give it a shot, and if you're still stuck, turn to the next section where you'll see how to write subqueries which can make complex queries such as this much simpler!

In [18]:
c = conn.cursor()
sql_str = """

SELECT employees.firstName, employees.lastName, products.productName, orderdetails.quantityOrdered, orders.orderDate
FROM employees
JOIN customers 
ON employees.employeeNumber = customers.salesRepEmployeeNumber
JOIN orders
ON customers.customerNumber = orders.customerNumber
JOIN orderdetails
ON orders.orderNumber = orderdetails.orderNumber
JOIN products
ON products.productCode = orderdetails.productCode
ORDER BY orders.orderDate DESC, employees.firstName, employees.lastName, products.productName, orderdetails.quantityOrdered;

"""

c.execute(sql_str).fetchall()

[('Gerard', 'Hernandez', '1926 Ford Fire Engine', '19', '2005-05-31'),
 ('Gerard', 'Hernandez', '1939 Cadillac Limousine', '26', '2005-05-31'),
 ('Gerard', 'Hernandez', '1940 Ford Pickup Truck', '54', '2005-05-31'),
 ('Gerard', 'Hernandez', '1940s Ford truck', '38', '2005-05-31'),
 ('Gerard', 'Hernandez', '1952 Alpine Renault 1300', '50', '2005-05-31'),
 ('Gerard', 'Hernandez', '1954 Greyhound Scenicruiser', '11', '2005-05-31'),
 ('Gerard', 'Hernandez', '1957 Chevy Pickup', '33', '2005-05-31'),
 ('Gerard',
  'Hernandez',
  '1958 Chevy Corvette Limited Edition',
  '31',
  '2005-05-31'),
 ('Gerard', 'Hernandez', '1958 Setra Bus', '49', '2005-05-31'),
 ('Gerard', 'Hernandez', '1962 LanciaA Delta 16V', '38', '2005-05-31'),
 ('Gerard', 'Hernandez', '1962 Volkswagen Microbus', '49', '2005-05-31'),
 ('Gerard', 'Hernandez', '1964 Mercedes Tour Bus', '38', '2005-05-31'),
 ('Gerard', 'Hernandez', '1970 Dodge Coronet', '55', '2005-05-31'),
 ('Gerard', 'Hernandez', '1980’s GM Manhattan Express', '41', '2005-05-31'),
 ('Gerard', 'Hernandez', '1982 Camaro Z28', '46', '2005-05-31'),
 ('Gerard', 'Hernandez', '1992 Ferrari 360 Spider red', '28', '2005-05-31'),
 ('Gerard',
  'Hernandez',
  '1996 Peterbilt 379 Stake Bed with Outrigger',
  '44',
  '2005-05-31'),
 ('Gerard', 'Hernandez', '1998 Chrysler Plymouth Prowler', '28', '2005-05-31'),
 ('Gerard',
  'Hernandez',
  'Diamond T620 Semi-Skirted Tanker',
  '18',
  '2005-05-31'),
 ('Pamela',
  'Castillo',
  '18th Century Vintage Horse Carriage',
  '21',
  '2005-05-30'),
 ('Pamela', 'Castillo', '1913 Ford Model T Speedster', '10', '2005-05-30'),
 ('Pamela', 'Castillo', '1917 Maxwell Touring Car', '21', '2005-05-30'),
 ('Pamela', 'Castillo', '1934 Ford V8 Coupe', '31', '2005-05-30'),
 ('Pamela', 'Castillo', '1936 Chrysler Airflow', '28', '2005-05-30'),
 ('Steve',
  'Patterson',
  '1936 Mercedes-Benz 500K Special Roadster',
  '25',
  '2005-05-30'),
 ('Steve', 'Patterson', '1937 Lincoln Berline', '51', '2005-05-30'),
 ('Andy', 'Fixter', '1911 Ford Town Car', '36', '2005-05-29'),
 ('Andy', 'Fixter', '1917 Grand Touring Sedan', '37', '2005-05-29'),
 ('Andy', 'Fixter', '1932 Alfa Romeo 8C2300 Spider Sport', '66', '2005-05-29'),
 ('Andy', 'Fixter', '1932 Model A Ford J-Coupe', '45', '2005-05-29'),
 ('Andy', 'Fixter', '1936 Mercedes Benz 500k Roadster', '15', '2005-05-29'),
 ('Andy', 'Fixter', '1939 Chevrolet Deluxe Coupe', '45', '2005-05-29'),
 ('Andy', 'Fixter', '1949 Jaguar XK 120', '39', '2005-05-29'),
 ('Andy', 'Fixter', '1952 Citroen-15CV', '55', '2005-05-29'),
 ('Andy', 'Fixter', '1957 Ford Thunderbird', '36', '2005-05-29'),
 ('Andy', 'Fixter', '1966 Shelby Cobra 427 S/C', '37', '2005-05-29'),
 ('Andy', 'Fixter', '1969 Chevrolet Camaro Z28', '35', '2005-05-29'),
 ('Andy', 'Fixter', '1970 Chevy Chevelle SS 454', '60', '2005-05-29'),
 ('Andy', 'Fixter', '2002 Chevy Corvette', '26', '2005-05-29'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK', '35', '2005-05-29'),
 ('Leslie',
  'Jennings',
  '1938 Cadillac V-16 Presidential Limousine',
  '40',
  '2005-05-29'),
 ('Pamela', 'Castillo', '1948 Porsche 356-A Roadster', '39', '2005-05-17'),
 ('Pamela', 'Castillo', '1948 Porsche Type 356 Roadster', '43', '2005-05-17'),
 ('Pamela', 'Castillo', '1956 Porsche 356A Coupe', '70', '2005-05-17'),
 ('Pamela', 'Castillo', '1965 Aston Martin DB5', '37', '2005-05-17'),
 ('Pamela', 'Castillo', '1968 Dodge Charger', '10', '2005-05-17'),
 ('Pamela', 'Castillo', '1968 Ford Mustang', '12', '2005-05-17'),
 ('Pamela', 'Castillo', '1969 Dodge Charger', '32', '2005-05-17'),
 ('Pamela', 'Castillo', '1970 Plymouth Hemi Cuda', '34', '2005-05-17'),
 ('Pamela', 'Castillo', '1971 Alpine Renault 1600s', '55', '2005-05-17'),
 ('Pamela', 'Castillo', '1982 Lamborghini Diablo', '15', '2005-05-17'),
 ('Pamela', 'Castillo', '1992 Ferrari 360 Spider red', '35', '2005-05-17'),
 ('Pamela', 'Castillo', '1993 Mazda RX-7', '38', '2005-05-17'),
 ('Pamela', 'Castillo', '1995 Honda Civic', '34', '2005-05-17'),
 ('Pamela', 'Castillo', '1999 Indy 500 Monte Carlo SS', '55', '2005-05-17'),
 ('Peter', 'Marsh', '1957 Corvette Convertible', '28', '2005-05-16'),
 ('Peter', 'Marsh', '1957 Vespa GS150', '33', '2005-05-16'),
 ('Peter', 'Marsh', '1961 Chevrolet Impala', '10', '2005-05-16'),
 ('Peter', 'Marsh', '1969 Dodge Super Bee', '16', '2005-05-16'),
 ('Peter', 'Marsh', '1974 Ducati 350 Mk3 Desmo', '50', '2005-05-16'),
 ('Peter', 'Marsh', '1976 Ford Gran Torino', '27', '2005-05-16'),
 ('Peter', 'Marsh', '1982 Ducati 900 Monster', '52', '2005-05-16'),
 ('Peter', 'Marsh', '1982 Ducati 996 R', '43', '2005-05-16'),
 ('Peter', 'Marsh', '2002 Yamaha YZR M1', '40', '2005-05-16'),
 ('Gerard',
  'Hernandez',
  '1936 Harley Davidson El Knucklehead',
  '36',
  '2005-05-13'),
 ('Gerard',
  'Hernandez',
  '1969 Harley Davidson Ultimate Chopper',
  '66',
  '2005-05-13'),
 ('Gerard', 'Hernandez', '1996 Moto Guzzi 1100i', '45', '2005-05-13'),
 ('Gerard', 'Hernandez', '1997 BMW R 1100 S', '35', '2005-05-13'),
 ('Gerard', 'Hernandez', '2002 Suzuki XREO', '21', '2005-05-13'),
 ('Gerard',
  'Hernandez',
  '2003 Harley-Davidson Eagle Drag Bike',
  '56',
  '2005-05-13'),
 ('Pamela', 'Castillo', '1900s Vintage Tri-Plane', '48', '2005-05-10'),
 ('Pamela',
  'Castillo',
  '1928 British Royal Navy Airplane',
  '47',
  '2005-05-10'),
 ('Pamela', 'Castillo', '1928 Ford Phaeton Deluxe', '26', '2005-05-10'),
 ('Pamela', 'Castillo', '1930 Buick Marquette Phaeton', '37', '2005-05-10'),
 ('Pamela', 'Castillo', '1960 BSA Gold Star DBD34', '32', '2005-05-10'),
 ('Pamela', 'Castillo', '1980s Black Hawk Helicopter', '24', '2005-05-10'),
 ('Pamela', 'Castillo', '1997 BMW F650 ST', '45', '2005-05-10'),
 ('Pamela', 'Castillo', 'ATA: B757-300', '41', '2005-05-10'),
 ('Pamela', 'Castillo', 'America West Airlines B757-200', '22', '2005-05-10'),
 ('Pamela', 'Castillo', 'American Airlines: B767-300', '23', '2005-05-10'),
 ('Pamela', 'Castillo', 'American Airlines: MD-11S', '43', '2005-05-10'),
 ('Pamela', 'Castillo', 'Corsair F4U ( Bird Cage)', '18', '2005-05-10'),
 ('Pamela', 'Castillo', 'F/A 18 Hornet 1/72', '39', '2005-05-10'),
 ('Pamela', 'Castillo', 'P-51-D Mustang', '15', '2005-05-10'),
 ('Andy', 'Fixter', '1900s Vintage Bi-Plane', '21', '2005-05-09'),
 ('Andy', 'Fixter', '1937 Horch 930V Limousine', '18', '2005-05-09'),
 ('Andy',
  'Fixter',
  '1941 Chevrolet Special Deluxe Cabriolet',
  '51',
  '2005-05-09'),
 ('Andy', 'Fixter', 'Boeing X-32A JSF', '42', '2005-05-09'),
 ('Andy', 'Fixter', 'HMS Bounty', '32', '2005-05-09'),
 ('Steve', 'Patterson', '18th century schooner', '43', '2005-05-06'),
 ('Steve', 'Patterson', '1903 Ford Model A', '41', '2005-05-06'),
 ('Steve', 'Patterson', '1904 Buick Runabout', '56', '2005-05-06'),
 ('Steve',
  'Patterson',
  '1912 Ford Model T Delivery Wagon',
  '60',
  '2005-05-06'),
 ('Steve', 'Patterson', '1940 Ford Delivery Sedan', '51', '2005-05-06'),
 ('Steve', 'Patterson', '1972 Alfa Romeo GTA', '49', '2005-05-06'),
 ('Steve', 'Patterson', '1999 Yamaha Speed Boat', '44', '2005-05-06'),
 ('Steve', 'Patterson', 'Collectable Wooden Train', '48', '2005-05-06'),
 ('Steve', 'Patterson', 'Pont Yacht', '47', '2005-05-06'),
 ('Steve', 'Patterson', 'The Mayflower', '34', '2005-05-06'),
 ('Steve', 'Patterson', 'The Queen Mary', '40', '2005-05-06'),
 ('Steve', 'Patterson', 'The Schooner Bluenose', '37', '2005-05-06'),
 ('Steve', 'Patterson', 'The Titanic', '28', '2005-05-06'),
 ('Steve', 'Patterson', 'The USS Constitution Ship', '31', '2005-05-06'),
 ('George',
  'Vanauf',
  "1950's Chicago Surface Lines Streetcar",
  '24',
  '2005-05-05'),
 ('George', 'Vanauf', '1962 City of Detroit Streetcar', '51', '2005-05-05'),
 ('George', 'Vanauf', '1969 Corvair Monza', '47', '2005-05-05'),
 ('George', 'Vanauf', '1969 Ford Falcon', '22', '2005-05-05'),
 ('George', 'Vanauf', '1970 Triumph Spitfire', '49', '2005-05-05'),
 ('George', 'Vanauf', '2001 Ferrari Enzo', '36', '2005-05-05'),
 ('Gerard', 'Hernandez', '1926 Ford Fire Engine', '47', '2005-05-03'),
 ('Gerard', 'Hernandez', '1954 Greyhound Scenicruiser', '19', '2005-05-03'),
 ('Gerard', 'Hernandez', '1957 Chevy Pickup', '54', '2005-05-03'),
 ('Gerard',
  'Hernandez',
  '1958 Chevy Corvette Limited Edition',
  '30',
  '2005-05-03'),
 ('Gerard', 'Hernandez', '1962 Volkswagen Microbus', '70', '2005-05-03'),
 ('Gerard', 'Hernandez', '1964 Mercedes Tour Bus', '56', '2005-05-03'),
 ('Gerard', 'Hernandez', '1970 Dodge Coronet', '21', '2005-05-03'),
 ('Gerard', 'Hernandez', '1992 Ferrari 360 Spider red', '60', '2005-05-03'),
 ('Gerard',
  'Hernandez',
  '1992 Porsche Cayenne Turbo Silver',
  '31',
  '2005-05-03'),
 ('Gerard', 'Hernandez', '1998 Chrysler Plymouth Prowler', '41', '2005-05-03'),
 ('Gerard',
  'Hernandez',
  'Diamond T620 Semi-Skirted Tanker',
  '26',
  '2005-05-03'),
 ('Foon Yue', 'Tseng', '1939 Cadillac Limousine', '35', '2005-05-01'),
 ('Foon Yue', 'Tseng', '1940 Ford Pickup Truck', '27', '2005-05-01'),
 ('Foon Yue', 'Tseng', '1940s Ford truck', '46', '2005-05-01'),
 ('Foon Yue', 'Tseng', '1952 Alpine Renault 1300', '23', '2005-05-01'),
 ('Foon Yue', 'Tseng', '1958 Setra Bus', '40', '2005-05-01'),
 ('Foon Yue', 'Tseng', '1962 LanciaA Delta 16V', '27', '2005-05-01'),
 ('Foon Yue', 'Tseng', '1980’s GM Manhattan Express', '26', '2005-05-01'),
 ('Foon Yue', 'Tseng', '1982 Camaro Z28', '34', '2005-05-01'),
 ('Foon Yue',
  'Tseng',
  '1996 Peterbilt 379 Stake Bed with Outrigger',
  '27',
  '2005-05-01'),
 ('Peter', 'Marsh', '18th Century Vintage Horse Carriage', '34', '2005-04-29'),
 ('Peter', 'Marsh', '1913 Ford Model T Speedster', '47', '2005-04-29'),
 ('Peter', 'Marsh', '1917 Maxwell Touring Car', '44', '2005-04-29'),
 ('Peter', 'Marsh', '1928 Mercedes-Benz SSK', '56', '2005-04-29'),
 ('Peter', 'Marsh', '1934 Ford V8 Coupe', '53', '2005-04-29'),
 ('Peter', 'Marsh', '1936 Chrysler Airflow', '50', '2005-04-29'),
 ('Peter',
  'Marsh',
  '1936 Mercedes-Benz 500K Special Roadster',
  '44',
  '2005-04-29'),
 ('Peter', 'Marsh', '1937 Lincoln Berline', '65', '2005-04-29'),
 ('Peter',
  'Marsh',
  '1938 Cadillac V-16 Presidential Limousine',
  '31',
  '2005-04-29'),
 ('Peter', 'Marsh', '1932 Model A Ford J-Coupe', '6', '2005-04-23'),
 ('Peter', 'Marsh', '1939 Chevrolet Deluxe Coupe', '61', '2005-04-23'),
 ('Leslie', 'Jennings', '1911 Ford Town Car', '42', '2005-04-22'),
 ('Leslie', 'Jennings', '1917 Grand Touring Sedan', '76', '2005-04-22'),
 ('Leslie',
  'Jennings',
  '1932 Alfa Romeo 8C2300 Spider Sport',
  '6',
  '2005-04-22'),
 ('Leslie', 'Jennings', '1949 Jaguar XK 120', '76', '2005-04-22'),
 ('Leslie', 'Jennings', '1952 Citroen-15CV', '59', '2005-04-22'),
 ('Leslie', 'Jennings', '1957 Ford Thunderbird', '66', '2005-04-22'),
 ('Leslie', 'Jennings', '1965 Aston Martin DB5', '59', '2005-04-22'),
 ('Leslie', 'Jennings', '1966 Shelby Cobra 427 S/C', '64', '2005-04-22'),
 ('Leslie', 'Jennings', '1969 Chevrolet Camaro Z28', '13', '2005-04-22'),
 ('Leslie', 'Jennings', '1970 Chevy Chevelle SS 454', '26', '2005-04-22'),
 ('Leslie', 'Jennings', '1999 Indy 500 Monte Carlo SS', '41', '2005-04-22'),
 ('Leslie', 'Jennings', '2002 Chevy Corvette', '43', '2005-04-22'),
 ('Mami', 'Nishi', '1936 Mercedes Benz 500k Roadster', '15', '2005-04-22'),
 ('Pamela', 'Castillo', '1948 Porsche Type 356 Roadster', '65', '2005-04-15'),
 ('Pamela', 'Castillo', '1993 Mazda RX-7', '61', '2005-04-15'),
 ('Pamela', 'Castillo', '1995 Honda Civic', '48', '2005-04-15'),
 ('Gerard', 'Hernandez', '1948 Porsche 356-A Roadster', '61', '2005-04-14'),
 ('Gerard', 'Hernandez', '1956 Porsche 356A Coupe', '76', '2005-04-14'),
 ('Gerard', 'Hernandez', '1969 Dodge Charger', '97', '2005-04-14'),
 ('Gerard', 'Hernandez', '1982 Lamborghini Diablo', '47', '2005-04-14'),
 ('Gerard', 'Hernandez', '1992 Ferrari 360 Spider red', '55', '2005-04-14'),
 ('Larry', 'Bott', '1957 Vespa GS150', '36', '2005-04-08'),
 ('Larry',
  'Bott',
  '1969 Harley Davidson Ultimate Chopper',
  '24',
  '2005-04-08'),
 ('Larry', 'Bott', '1974 Ducati 350 Mk3 Desmo', '45', '2005-04-08'),
 ('Larry', 'Bott', '1982 Ducati 900 Monster', '27', '2005-04-08'),
 ('Larry', 'Bott', '1982 Ducati 996 R', '30', '2005-04-08'),
 ('Larry', 'Bott', '1997 BMW R 1100 S', '46', '2005-04-08'),
 ('Larry', 'Bott', '2002 Suzuki XREO', '66', '2005-04-08'),
 ('Larry', 'Bott', '2002 Yamaha YZR M1', '31', '2005-04-08'),
 ('Larry', 'Bott', '2003 Harley-Davidson Eagle Drag Bike', '66', '2005-04-08'),
 ('Peter', 'Marsh', '1957 Corvette Convertible', '48', '2005-04-08'),
 ('Peter', 'Marsh', '1961 Chevrolet Impala', '48', '2005-04-08'),
 ('Peter', 'Marsh', '1968 Dodge Charger', '43', '2005-04-08'),
 ('Peter', 'Marsh', '1968 Ford Mustang', '64', '2005-04-08'),
 ('Peter', 'Marsh', '1969 Dodge Super Bee', '90', '2005-04-08'),
 ('Peter', 'Marsh', '1970 Plymouth Hemi Cuda', '77', '2005-04-08'),
 ('Peter', 'Marsh', '1971 Alpine Renault 1600s', '49', '2005-04-08'),
 ('Peter', 'Marsh', '1976 Ford Gran Torino', '28', '2005-04-08'),
 ('Loui', 'Bondur', '1936 Harley Davidson El Knucklehead', '55', '2005-04-07'),
 ('Loui', 'Bondur', '1960 BSA Gold Star DBD34', '59', '2005-04-07'),
 ('Loui', 'Bondur', '1996 Moto Guzzi 1100i', '45', '2005-04-07'),
 ('George', 'Vanauf', '1900s Vintage Tri-Plane', '52', '2005-04-03'),
 ('George', 'Vanauf', '1928 British Royal Navy Airplane', '38', '2005-04-03'),
 ('George', 'Vanauf', '1928 Ford Phaeton Deluxe', '62', '2005-04-03'),
 ('George', 'Vanauf', '1930 Buick Marquette Phaeton', '56', '2005-04-03'),
 ('George', 'Vanauf', '1997 BMW F650 ST', '49', '2005-04-03'),
 ('George', 'Vanauf', 'ATA: B757-300', '21', '2005-04-03'),
 ('George', 'Vanauf', 'America West Airlines B757-200', '85', '2005-04-03'),
 ('George', 'Vanauf', 'American Airlines: B767-300', '11', '2005-04-03'),
 ('George', 'Vanauf', 'American Airlines: MD-11S', '40', '2005-04-03'),
 ('George', 'Vanauf', 'Corsair F4U ( Bird Cage)', '64', '2005-04-03'),
 ('George', 'Vanauf', 'F/A 18 Hornet 1/72', '77', '2005-04-03'),
 ('George', 'Vanauf', 'P-51-D Mustang', '42', '2005-04-03'),
 ('Leslie', 'Jennings', '1900s Vintage Bi-Plane', '24', '2005-04-01'),
 ('Leslie', 'Jennings', '1937 Horch 930V Limousine', '38', '2005-04-01'),
 ('Leslie', 'Jennings', '1940 Ford Delivery Sedan', '42', '2005-04-01'),
 ('Leslie',
  'Jennings',
  '1941 Chevrolet Special Deluxe Cabriolet',
  '58',
  '2005-04-01'),
 ('Leslie', 'Jennings', '1972 Alfa Romeo GTA', '64', '2005-04-01'),
 ('Leslie', 'Jennings', '1980s Black Hawk Helicopter', '34', '2005-04-01'),
 ('Leslie', 'Jennings', '1999 Yamaha Speed Boat', '30', '2005-04-01'),
 ('Leslie', 'Jennings', 'Boeing X-32A JSF', '20', '2005-04-01'),
 ('Leslie', 'Jennings', 'HMS Bounty', '46', '2005-04-01'),
 ('Peter', 'Marsh', '1936 Harley Davidson El Knucklehead', '30', '2005-04-01'),
 ('Peter', 'Marsh', '1960 BSA Gold Star DBD34', '58', '2005-04-01'),
 ('Peter',
  'Marsh',
  '1969 Harley Davidson Ultimate Chopper',
  '40',
  '2005-04-01'),
 ('Peter', 'Marsh', '1996 Moto Guzzi 1100i', '51', '2005-04-01'),
 ('Peter', 'Marsh', '1997 BMW F650 ST', '32', '2005-04-01'),
 ('Peter', 'Marsh', '1997 BMW R 1100 S', '57', '2005-04-01'),
 ('Peter', 'Marsh', '2002 Suzuki XREO', '29', '2005-04-01'),
 ('Peter',
  'Marsh',
  '2003 Harley-Davidson Eagle Drag Bike',
  '22',
  '2005-04-01'),
 ('Loui', 'Bondur', '1900s Vintage Bi-Plane', '28', '2005-03-30'),
 ('Loui', 'Bondur', '1900s Vintage Tri-Plane', '45', '2005-03-30'),
 ('Loui', 'Bondur', '1928 British Royal Navy Airplane', '43', '2005-03-30'),
 ('Loui', 'Bondur', '1928 Ford Phaeton Deluxe', '22', '2005-03-30'),
 ('Loui', 'Bondur', '1930 Buick Marquette Phaeton', '49', '2005-03-30'),
 ('Loui', 'Bondur', '1937 Horch 930V Limousine', '34', '2005-03-30'),
 ('Loui',
  'Bondur',
  '1941 Chevrolet Special Deluxe Cabriolet',
  '45',
  '2005-03-30'),
 ('Loui', 'Bondur', '1980s Black Hawk Helicopter', '33', '2005-03-30'),
 ('Loui', 'Bondur', '1999 Yamaha Speed Boat', '28', '2005-03-30'),
 ('Loui', 'Bondur', 'ATA: B757-300', '23', '2005-03-30'),
 ('Loui', 'Bondur', 'America West Airlines B757-200', '22', '2005-03-30'),
 ('Loui', 'Bondur', 'American Airlines: B767-300', '47', '2005-03-30'),
 ('Loui', 'Bondur', 'American Airlines: MD-11S', '36', '2005-03-30'),
 ('Loui', 'Bondur', 'Boeing X-32A JSF', '34', '2005-03-30'),
 ('Loui', 'Bondur', 'Corsair F4U ( Bird Cage)', '41', '2005-03-30'),
 ('Loui', 'Bondur', 'F/A 18 Hornet 1/72', '29', '2005-03-30'),
 ('Loui', 'Bondur', 'HMS Bounty', '36', '2005-03-30'),
 ('Loui', 'Bondur', 'P-51-D Mustang', '34', '2005-03-30'),
 ('Gerard', 'Hernandez', 'Pont Yacht', '34', '2005-03-28'),
 ('Gerard', 'Hernandez', 'The Mayflower', '32', '2005-03-28'),
 ('Gerard', 'Hernandez', 'The Queen Mary', '36', '2005-03-28'),
 ('Gerard', 'Hernandez', 'The Titanic', '48', '2005-03-28'),
 ('Gerard', 'Hernandez', 'The USS Constitution Ship', '22', '2005-03-28'),
 ('Leslie', 'Jennings', '18th century schooner', '49', '2005-03-23'),
 ('Leslie', 'Jennings', '1903 Ford Model A', '33', '2005-03-23'),
 ('Leslie', 'Jennings', '1904 Buick Runabout', '45', '2005-03-23'),
 ('Leslie',
  'Jennings',
  '1912 Ford Model T Delivery Wagon',
  '27',
  '2005-03-23'),
 ('Leslie', 'Jennings', '1940 Ford Delivery Sedan', '37', '2005-03-23'),
 ('Leslie', 'Jennings', '1969 Ford Falcon', '33', '2005-03-23'),
 ('Leslie', 'Jennings', 'Collectable Wooden Train', '24', '2005-03-23'),
 ('Leslie', 'Jennings', 'The Schooner Bluenose', '39', '2005-03-23'),
 ('Loui', 'Bondur', '1962 City of Detroit Streetcar', '45', '2005-03-17'),
 ('Loui', 'Bondur', '1972 Alfa Romeo GTA', '32', '2005-03-17'),
 ('Loui', 'Bondur', '2001 Ferrari Enzo', '33', '2005-03-17'),
 ('Loui', 'Bondur', 'Diamond T620 Semi-Skirted Tanker', '46', '2005-03-17'),
 ('Gerard',
  'Hernandez',
  "1950's Chicago Surface Lines Streetcar",
  '30',
  '2005-03-15'),
 ('Gerard', 'Hernandez', '1954 Greyhound Scenicruiser', '36', '2005-03-15'),
 ('Gerard',
  'Hernandez',
  '1958 Chevy Corvette Limited Edition',
  '46',
  '2005-03-15'),
 ('Gerard', 'Hernandez', '1970 Dodge Coronet', '31', '2005-03-15'),
 ('Gerard', 'Hernandez', '1970 Triumph Spitfire', '37', '2005-03-15'),
 ('Gerard', 'Hernandez', '1992 Ferrari 360 Spider red', '22', '2005-03-15'),
 ('Gerard',
  'Hernandez',
  '1992 Porsche Cayenne Turbo Silver',
  '37',
  '2005-03-15'),
 ('Peter', 'Marsh', '1936 Chrysler Airflow', '33', '2005-03-11'),
 ('Peter', 'Marsh', '1939 Cadillac Limousine', '44', '2005-03-11'),
 ('Peter', 'Marsh', '1940s Ford truck', '30', '2005-03-11'),
 ('Peter', 'Marsh', '1957 Chevy Pickup', '32', '2005-03-11'),
 ('Peter', 'Marsh', '1962 Volkswagen Microbus', '33', '2005-03-11'),
 ('Peter', 'Marsh', '1964 Mercedes Tour Bus', '38', '2005-03-11'),
 ('Peter', 'Marsh', '1969 Corvair Monza', '35', '2005-03-11'),
 ('Peter', 'Marsh', '1980’s GM Manhattan Express', '38', '2005-03-11'),
 ('Peter', 'Marsh', '1982 Camaro Z28', '21', '2005-03-11'),
 ('Peter',
  'Marsh',
  '1996 Peterbilt 379 Stake Bed with Outrigger',
  '31',
  '2005-03-11'),
 ('Peter', 'Marsh', '1998 Chrysler Plymouth Prowler', '20', '2005-03-11'),
 ('Pamela',
  'Castillo',
  '18th Century Vintage Horse Carriage',
  '29',
  '2005-03-10'),
 ('Pamela', 'Castillo', '1917 Maxwell Touring Car', '36', '2005-03-10'),
 ('Pamela', 'Castillo', '1934 Ford V8 Coupe', '37', '2005-03-10'),
 ('Andy', 'Fixter', '1913 Ford Model T Speedster', '32', '2005-03-09'),
 ('Andy', 'Fixter', '1926 Ford Fire Engine', '44', '2005-03-09'),
 ('Andy',
  'Fixter',
  '1936 Mercedes-Benz 500K Special Roadster',
  '42',
  '2005-03-09'),
 ('Andy', 'Fixter', '1937 Lincoln Berline', '35', '2005-03-09'),
 ('Andy',
  'Fixter',
  '1938 Cadillac V-16 Presidential Limousine',
  '24',
  '2005-03-09'),
 ('Andy', 'Fixter', '1939 Chevrolet Deluxe Coupe', '33', '2005-03-09'),
 ('Andy', 'Fixter', '1940 Ford Pickup Truck', '29', '2005-03-09'),
 ('Andy', 'Fixter', '1952 Alpine Renault 1300', '24', '2005-03-09'),
 ('Andy', 'Fixter', '1958 Setra Bus', '39', '2005-03-09'),
 ('Andy', 'Fixter', '1962 LanciaA Delta 16V', '37', '2005-03-09'),
 ('Leslie', 'Jennings', '1928 Mercedes-Benz SSK', '26', '2005-03-04'),
 ('Leslie', 'Jennings', '1932 Model A Ford J-Coupe', '31', '2005-03-04'),

## Summary

In this lab, you practiced your knowledge on one-to-many and many-to-many relationships!